### ISSUE TITLE
Question: Can I use a json or csv file as a data source for deployment?

### ISSUE THREAD

**Issue by MortalCatalyst** [yaph/logya#78]
Can I use a json or csv file as a data source for deployment?

So I could use data in an interactive visualization without needing to get it from elsewhere.

**Comment by yaph** [comment]
You can have data in JSON or CSV format in the `static` directory and then access it in JavaScript. For example the file `static/data.json` could be loaded with D3 like `d3.json('/data.json', ...)`.

**Comment by MortalCatalyst** [comment]
Cool and it would be available to template's like jinja loops if wanting to utilize it that way?

**Comment by yaph** [comment]
No, but you can either generate content files from datasets or directly generate HTML files to the deploy directory using the logya API. That is not documented at the moment though.

**Comment by MortalCatalyst** [comment]
Sorry one last question I promise, I am asking because I find logya the cleanest solution out there and flexible. 
Is there a plugin mechanism to write say a mako or jade template plugin?

**Comment by yaph** [comment]
No, there were some hooks in a previous version, but I removed them in favor of writing custom scripts, that import Logya functions. I personally don't use other template engines than jinja, but if support for other engines can be added in a way that does not add a lot of complexity, I'm certainly open to it.

**Comment by MortalCatalyst** [comment]
Cool will start with jinja and explore a bit in logya and take it from there. Thanks for your time.

**Comment by yaph** [comment]
No problem and thanks for the feedback!
